### ISSUE TITLE
[Aviation/HangarGates - Odd Bug] CE - Main gives an error when starting the game, makes it crash

### ISSUE THREAD

**Issue by CommanderBondt** [Eagle-Studios/CE_Mods#3]
[ArmaReport_Log_20241126T132126_romai.zip](https://github.com/user-attachments/files/17920154/ArmaReport_Log_20241126T132126_romai.zip)
![image](https://github.com/user-attachments/assets/1f4766e5-f340-4b37-9ffc-7db9060dac6b)

Hello, when I start my game with your mods and their dependencies, I get an error and the game crashes :
"Include file CE_MAIN\cfgPatches_Automatic.hpp not found" (see screenshot)

I start it with my whole modpack and your mods (CE - Main, CE - Aviation, and CE - RHS USAF Upgrades and Improvements)
Even with just your mods + their dependencies it crashes

**Comment by Eagle-Studios** [comment]
Interesting seems HangarGates doesnt like that :/
Removed the issue, its only a mod with a composition inside it.

**Comment by Jam1bob** [comment]
Still getting the same error message as originally posted!

**Comment by CommanderBondt** [comment]
Same as Jam1bob, still getting the same error and crashing
[ArmaReport_Log_20241126T234443_romai.zip](https://github.com/user-attachments/files/17926873/ArmaReport_Log_20241126T234443_romai.zip)

**Comment by Eagle-Studios** [comment]
Okay, how very odd. Launching myself, yields no issues. 
I shall look further into this.

**Comment by Eagle-Studios** [comment]
@CommanderBondt @Jam1bob I have just pushed a new update; can you download and check it that works for you both? - thanks :)

**Comment by CommanderBondt** [comment]
Still getting the same error and crashing on startup :(
[ArmaReport_Log_20241127T154621_romai.zip](https://github.com/user-attachments/files/17936896/ArmaReport_Log_20241127T154621_romai.zip)

**Comment by CommanderBondt** [comment]
Without "CE - RHSUSAF Edited" the game starts without a problem
Sorry but I don't know what a RPT is

**Comment by Jam1bob** [comment]
Apologies, I'm late to the party!
So if can load the game with:
CE - Main
CE - Aviation
CE - Flares

As soon as I add:
CE - RHSUSAF Edited, this is when I get the error message from the original picture.

Hope this helps?

**Comment by Eagle-Studios** [comment]
Yeh, sorta. 
Its more just reinforcement at this point; but thank you anyway

**Comment by Eagle-Studios** [comment]
Just pushed another update. Please let me know now. (RHSUSAF Edited)

**Comment by Jam1bob** [comment]
Everything for me is working perfectly again! Thankyou

**Comment by Eagle-Studios** [comment]
Blame Mikerotools being weird ahahahah (All I did was repack it)

**Comment by CommanderBondt** [comment]
Seems to be working fine now, thank you for the work :)
